name: gnt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # Core GDAL and geospatial dependencies
  - gdal
  - rasterio>=1.3.0
  - pyproj>=3.4.0
  - shapely>=2.0.0
  - geopandas>=0.12.0
  
  # Data processing and scientific computing
  - numpy>=1.22.0
  - pandas>=1.5.0
  - scipy>=1.9.0
  - xarray>=2023.1.0
  - pyarrow>=8.0.0
  - dask>=2023.1.0
  - distributed>=2023.1.0
  
  # HDF and NetCDF support
  - hdf4
  - hdf5
  - h5py>=3.7.0
  - netcdf4>=1.6.0
  - libnetcdf
  - libgdal-hdf4
  
  # Storage formats
  - zarr>=2.13.0
  - fsspec>=2022.11.0
  - gcsfs>=2023.1.0
  - numcodecs>=0.11.0
  - python-blosc>=1.11.0
  - blosc
  - c-blosc2
  
  # Web scraping and download dependencies
  - selenium
  - beautifulsoup4
  - requests
  - python-dotenv
  - google-cloud-storage
  
  # Testing utilities
  - pytest
  - requests-mock
  
  # Additional utilities
  - tqdm>=4.64.0
  - pyyaml>=6.0
  
  # Pip-specific packages
  - pip
  - pip:
    - rioxarray>=0.13.0
    - google-auth>=2.15.0