#!/bin/bash
# Generated by orchestration/slurm/generate_slurm_scripts.py from jobs.yaml.
# Do not hand-edit -- edit jobs.yaml and regenerate.
#
# modis-fetch: runs on whatever host has outbound internet egress (a scicore
# login/transfer node, a workstation, a cloud VM) -- NOT submitted via sbatch.
# See docs/design/09-integrated-pipeline.md §9 / docs/design/08-hpc-transfer.md.

set -euo pipefail

mkdir -p "./log/preprocess/modis"
cd /scicore/home/meiera/schulz0022/projects/growth-and-temperature

/scicore/home/meiera/schulz0022/miniforge-pypy3/envs/src/bin/python "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/run.py" pipeline run \
    --config "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/orchestration/configs/data.yaml" \
    --source modis \
    --step fetch \
    ${PIPELINE_OVERRIDE:+--override} \
    --debug

echo "fetch complete -- pushing results to scicore"
/scicore/home/meiera/schulz0022/miniforge-pypy3/envs/src/bin/python "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/run.py" pipeline transfer \
    --config "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/orchestration/configs/data.yaml" \
    --source modis \
    --step fetch \
    --direction push
