#!/bin/bash
#SBATCH --job-name=eog-dmsp-prepare
#SBATCH --output=./log/preprocess/eog_dmsp/%x-%j.out
#SBATCH --error=./log/preprocess/eog_dmsp/%x-%j.err
#SBATCH --time=06:00:00
#SBATCH --qos=6hours
#SBATCH --cpus-per-task=8
#SBATCH --mem=128G

# Generated by orchestration/slurm/generate_slurm_scripts.py from jobs.yaml.
# Do not hand-edit -- edit jobs.yaml and regenerate.

mkdir -p "./log/preprocess/eog_dmsp"
cd /scicore/home/meiera/schulz0022/projects/growth-and-temperature

# Activate conda environment
eval "$(/scicore/home/meiera/schulz0022/miniforge-pypy3/bin/conda shell.bash hook)"
conda activate src

# --override toggle -- either of these works:
#   sbatch <this script>.sh --override
#   sbatch --export=ALL,PIPELINE_OVERRIDE=1 <this script>.sh
OVERRIDE_FLAG=""
for _arg in "$@"; do
    if [ "$_arg" = "--override" ]; then
        OVERRIDE_FLAG="--override"
    fi
done
if [ -n "${PIPELINE_OVERRIDE:-}" ]; then
    OVERRIDE_FLAG="--override"
fi

/scicore/home/meiera/schulz0022/miniforge-pypy3/envs/src/bin/python "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/run.py" data run \
    --config "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/orchestration/configs/data.yaml" \
    --source eog_dmsp \
    --step prepare \
    $OVERRIDE_FLAG \
    --debug
