#!/bin/bash
#SBATCH --job-name=esacci-preprocess-annual
#SBATCH --output=./log/preprocess/esacci/%x-%j.out
#SBATCH --error=./log/preprocess/esacci/%x-%j.err
#SBATCH --time=1-00:00:00
#SBATCH --qos=1day
#SBATCH --cpus-per-task=4
#SBATCH --mem=128G

# Generated by orchestration/slurm/generate_slurm_scripts.py from jobs.yaml.
# Do not hand-edit -- edit jobs.yaml and regenerate.

mkdir -p "./log/preprocess/esacci"
cd /scicore/home/meiera/schulz0022/projects/growth-and-temperature

# Activate conda environment
eval "$(/scicore/home/meiera/schulz0022/miniforge-pypy3/bin/conda shell.bash hook)"
conda activate src

# Calculate memory limit (leave some buffer for system - 60% of allocated)
MEMORY_LIMIT_GB=$(echo "scale=0; $SLURM_MEM_PER_NODE * 0.6 / 1024" | bc)

/scicore/home/meiera/schulz0022/miniforge-pypy3/envs/src/bin/python "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/run.py" preprocess run \
    --config "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/orchestration/configs/data.yaml" \
    --source esacci \
    --stage annual \
    --dask-threads $SLURM_CPUS_PER_TASK \
    --dask-memory-limit "${MEMORY_LIMIT_GB}GiB" \
    --temp-dir "/scratch/schulz0022/esacci_${SLURM_JOB_ID}" \
    --dashboard-port 8787 \
    --debug
