#!/bin/bash
#SBATCH --job-name=gadm-prepare
#SBATCH --output=./log/preprocess/gadm/%x-%j.out
#SBATCH --error=./log/preprocess/gadm/%x-%j.err
#SBATCH --partition=scicore
#SBATCH --time=00:30:00
#SBATCH --qos=30min
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G

# Generated by orchestration/slurm/generate_slurm_scripts.py from jobs.yaml.
# Do not hand-edit -- edit jobs.yaml and regenerate.

mkdir -p "./log/preprocess/gadm"
cd /scicore/home/meiera/schulz0022/projects/growth-and-temperature

# Activate conda environment
eval "$(/scicore/home/meiera/schulz0022/miniforge-pypy3/bin/conda shell.bash hook)"
conda activate src

# Calculate memory limit (leave some buffer for system - 90% of allocated)
MEMORY_LIMIT_GB=$(echo "scale=0; $SLURM_MEM_PER_NODE * 0.9 / 1024" | bc)

/scicore/home/meiera/schulz0022/miniforge-pypy3/envs/src/bin/python "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/run.py" pipeline run \
    --config "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/orchestration/configs/data.yaml" \
    --source gadm \
    --step prepare \
    --dask-threads $SLURM_CPUS_PER_TASK \
    --dask-memory-limit "${MEMORY_LIMIT_GB}GiB" \
    --temp-dir "/scratch/schulz0022/gadm_${SLURM_JOB_ID}" \
    --dashboard-port 8787 \
    --debug
