#!/usr/bin/env python3
"""
Generate the per-source pipeline SLURM/egress scripts from
orchestration/slurm/jobs.yaml, so per-job differences (source, step,
resources, execution host) live in one small parameter table instead of
being copy-pasted across many near-identical files.

docs/design/09-integrated-pipeline.md §9: emits `run.py pipeline run
--source X --step Y` (replacing `preprocess run --source X --stage Y
[--subsource Z]`). `host: egress` (default `host: slurm`) folds what used to
be the hand-maintained `orchestration/scripts/modis-ingest-annual.sh` into
this generator: MODIS's PREPARE step needs outbound internet egress to
Planetary Computer, which scicore's SLURM compute nodes may not have, so it
is emitted as a plain shell script into `orchestration/scripts/` instead of
an `#SBATCH` script into `orchestration/slurm/`, with an optional
`transfer_after` step pushing results to scicore once done. After this
change, every per-source job the fleet runs -- including MODIS's -- is
covered by exactly one generator, with the execution-host difference modeled
as data rather than a directory convention.

Validates at generation time (this is the direct regression test for the
class of bug that motivated writing this generator in the first place --
see docs/design/09-integrated-pipeline.md §1's verified findings):
  - every job's `source` resolves in the source registry
    (src/data/sources/registry.py);
  - every job's `step` is one of that source's declared `steps`;
  - every job's `source` is a key in `orchestration/configs/data.yaml`'s
    `sources:` block.

Usage:
  python orchestration/slurm/generate_slurm_scripts.py          # write files
  python orchestration/slurm/generate_slurm_scripts.py --check  # drift check, no writes; exit 1 if any file would change

Scripts intentionally NOT covered here (left as hand-maintained, standalone
files): assemble_create.sh, assemble_update.sh, analysis.sh, compress.sh,
rechunk-zarr.sh, validate-backbone-subset.sh -- see jobs.yaml's header
comment. demean_modis.sh is dead (docs/design/04-ingest.md §6) and removed
in the migration's cutover step, not generated.
"""

import argparse
import difflib
import sys
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
SCRIPTS_DIR = REPO_ROOT / "orchestration" / "scripts"
JOBS_FILE = SCRIPT_DIR / "jobs.yaml"
DATA_YAML_FILE = REPO_ROOT / "orchestration" / "configs" / "data.yaml"

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

CONDA_HOOK = "/scicore/home/meiera/schulz0022/miniforge-pypy3/bin/conda"
PYTHON_BIN = "/scicore/home/meiera/schulz0022/miniforge-pypy3/envs/src/bin/python"
PROJECT_ROOT = "/scicore/home/meiera/schulz0022/projects/growth-and-temperature"
DEFAULT_DASHBOARD_PORT = 8787

GENERATED_MARKER = (
    "# Generated by orchestration/slurm/generate_slurm_scripts.py from jobs.yaml.\n"
    "# Do not hand-edit -- edit jobs.yaml and regenerate."
)


def _pipeline_run_cmd(job: dict) -> list[str]:
    simple = job.get("simple", False)
    dashboard_port = job.get("dashboard_port", DEFAULT_DASHBOARD_PORT)

    cmd_parts = [
        f'{PYTHON_BIN} "{PROJECT_ROOT}/run.py" pipeline run',
        f'--config "{PROJECT_ROOT}/orchestration/configs/data.yaml"',
        f"--source {job['source']}",
        f"--step {job['step']}",
    ]
    cmd_parts.extend(job.get("extra_args", []))
    if not simple:
        cmd_parts += [
            "--dask-threads $SLURM_CPUS_PER_TASK",
            '--dask-memory-limit "${MEMORY_LIMIT_GB}GiB"',
            f'--temp-dir "/scratch/schulz0022/{job["temp_dir_prefix"]}_${{SLURM_JOB_ID}}"',
            f"--dashboard-port {dashboard_port}",
        ]
    if job.get("debug", True):
        cmd_parts.append("--debug")
    return cmd_parts


def render_slurm_job(job: dict) -> str:
    name = job["name"]
    log_key = job["log_key"]
    simple = job.get("simple", False)

    lines = [
        "#!/bin/bash",
        f"#SBATCH --job-name={name}",
        f"#SBATCH --output=./log/preprocess/{log_key}/%x-%j.out",
        f"#SBATCH --error=./log/preprocess/{log_key}/%x-%j.err",
    ]
    if job.get("partition"):
        lines.append(f"#SBATCH --partition={job['partition']}")
    lines += [
        f"#SBATCH --time={job['time']}",
        f"#SBATCH --qos={job['qos']}",
        f"#SBATCH --cpus-per-task={job.get('cpus', 8)}",
        f"#SBATCH --mem={job['mem']}",
        "",
        GENERATED_MARKER,
        "",
        f'mkdir -p "./log/preprocess/{log_key}"',
        f"cd {PROJECT_ROOT}",
        "",
        "# Activate conda environment",
        f'eval "$({CONDA_HOOK} shell.bash hook)"',
        "conda activate src",
        "",
    ]

    if not simple:
        mem_fraction = job["mem_fraction"]
        mem_pct = int(round(mem_fraction * 100))
        lines += [
            f"# Calculate memory limit (leave some buffer for system - {mem_pct}% of allocated)",
            f'MEMORY_LIMIT_GB=$(echo "scale=0; $SLURM_MEM_PER_NODE * {mem_fraction} / 1024" | bc)',
            "",
        ]

    lines.append(" \\\n    ".join(_pipeline_run_cmd(job)))
    lines.append("")
    return "\n".join(lines)


def render_egress_job(job: dict) -> str:
    """A plain (non-SBATCH) script for a job that needs outbound internet
    egress a SLURM compute node may not have -- run manually on whatever
    host has that access, then (if `transfer_after` is set) push results to
    scicore before the corresponding SLURM job runs there."""
    name = job["name"]
    log_key = job["log_key"]

    lines = [
        "#!/bin/bash",
        GENERATED_MARKER,
        "#",
        f"# {name}: runs on whatever host has outbound internet egress (a scicore",
        "# login/transfer node, a workstation, a cloud VM) -- NOT submitted via sbatch.",
        "# See docs/design/09-integrated-pipeline.md §9 / docs/design/08-hpc-transfer.md.",
        "",
        "set -euo pipefail",
        "",
        f'mkdir -p "./log/preprocess/{log_key}"',
        f"cd {PROJECT_ROOT}",
        "",
    ]
    lines.append(" \\\n    ".join(_pipeline_run_cmd(job)))
    lines.append("")

    transfer_after = job.get("transfer_after")
    if transfer_after:
        lines += [
            f'echo "{job["step"]} complete -- pushing results to scicore"',
            " \\\n    ".join(
                [
                    f'{PYTHON_BIN} "{PROJECT_ROOT}/run.py" pipeline transfer',
                    f'--config "{PROJECT_ROOT}/orchestration/configs/data.yaml"',
                    f"--source {job['source']}",
                    f"--step {transfer_after}",
                    "--direction push",
                ]
            ),
            "",
        ]
    return "\n".join(lines)


def render_job(job: dict) -> tuple[str, Path]:
    """Return (rendered content, target path) for *job*."""
    host = job.get("host", "slurm")
    if host == "egress":
        return render_egress_job(job), SCRIPTS_DIR / f"{job['name']}.sh"
    if host == "slurm":
        return render_slurm_job(job), SCRIPT_DIR / f"{job['name']}.sh"
    raise ValueError(f"job {job['name']!r}: unknown host {host!r} (expected 'slurm' or 'egress')")


def load_jobs() -> list:
    with open(JOBS_FILE) as f:
        spec = yaml.safe_load(f)
    return spec["jobs"]


def _load_data_yaml_source_keys() -> set[str]:
    if not DATA_YAML_FILE.exists():
        return set()
    with open(DATA_YAML_FILE) as f:
        data = yaml.safe_load(f) or {}
    return set((data.get("sources") or {}).keys())


def _pipeline_run_argv(job: dict) -> list[str]:
    """The argv `_pipeline_run_cmd` would hand to `pipeline run`, with SLURM's
    shell-expanded values (``$SLURM_CPUS_PER_TASK``, etc.) replaced by dummy
    literals so it can be fed straight to argparse -- shlex can't split
    something that's only meaningful after the shell substitutes it."""
    import shlex

    parts = _pipeline_run_cmd(job)[1:]  # drop the "python .../run.py pipeline run" launcher token
    argv: list[str] = []
    for part in parts:
        part = (
            part.replace("$SLURM_CPUS_PER_TASK", "4")
            .replace('"${MEMORY_LIMIT_GB}GiB"', "4GiB")
            .replace('"/scratch/schulz0022/', '"/tmp/dummy_')
        )
        argv.extend(shlex.split(part))
    return argv


def validate_jobs(jobs: list) -> list[str]:
    """Return a list of error strings (empty if every job is valid)."""
    from src.data.sources import registry
    from src.data.sources.steps import PipelineStep

    errors = []
    data_yaml_sources = _load_data_yaml_source_keys()

    for job in jobs:
        name = job["name"]
        try:
            spec = registry.resolve(job["source"])
        except ValueError:
            errors.append(f"{name}: source '{job['source']}' is not registered in src/data/sources/registry.py")
            continue

        try:
            step = PipelineStep(job["step"])
        except ValueError:
            errors.append(f"{name}: unknown step '{job['step']}'")
            continue

        if step not in spec.steps:
            errors.append(
                f"{name}: source '{job['source']}' does not implement step '{job['step']}' "
                f"(declared steps: {[s.value for s in spec.steps]})"
            )

        if job["source"] not in data_yaml_sources:
            errors.append(f"{name}: source '{job['source']}' is not a key in orchestration/configs/data.yaml's sources: block")

        # Argparse round-trip: catches a job emitting a flag `pipeline run`
        # doesn't define (e.g. --dask-threads before it existed on this
        # parser) before it ever reaches a SLURM queue.
        from src.cli.main import build_parser

        try:
            build_parser().parse_args(["pipeline", "run", *_pipeline_run_argv(job)])
        except SystemExit:
            errors.append(f"{name}: rendered command does not parse against `pipeline run`'s argparse spec")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="report drift without writing files")
    args = parser.parse_args()

    jobs = load_jobs()
    names_seen = set()

    for job in jobs:
        name = job["name"]
        if name in names_seen:
            print(f"ERROR: duplicate job name {name!r} in jobs.yaml", file=sys.stderr)
            return 1
        names_seen.add(name)

    errors = validate_jobs(jobs)
    if errors:
        print("ERROR: jobs.yaml validation failed:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 1

    drift = False
    for job in jobs:
        rendered, target = render_job(job)

        if args.check:
            existing = target.read_text() if target.exists() else ""
            if existing != rendered:
                drift = True
                print(f"DRIFT: {target.relative_to(REPO_ROOT)}")
                diff = difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    rendered.splitlines(keepends=True),
                    fromfile=f"{target.name} (on disk)",
                    tofile=f"{target.name} (generated)",
                )
                sys.stdout.writelines(diff)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(rendered)
            target.chmod(0o755)
            print(f"wrote {target}")

    if args.check:
        if drift:
            print(f"\n{len(names_seen)} job(s) checked -- drift found, run without --check to regenerate.")
            return 1
        print(f"{len(names_seen)} job(s) checked -- no drift.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
