#!/usr/bin/env python3
"""
Generate the "preprocess" family of orchestration/slurm/*.sh scripts from
orchestration/slurm/jobs.yaml, so per-job differences (source, stage,
resources) live in one small parameter table instead of being copy-pasted
across ~16 near-identical files.

Why this exists: auditing the existing scripts while adding a new one
(validate-backbone-subset.sh) surfaced real bugs from that copy-paste
pattern, all fixed by construction here since there is now exactly one place
the invocation shape is written:

  - Every script in this family called `run.py preprocess --source ...`
    without the required `run` sub-subcommand
    (`src/cli/preprocess/commands.py` has required `run`/`transfer`
    sub-subcommands since commit 7da6da6) -- every one of them was failing
    immediately with an argparse error before doing any work.
  - `esacci-preprocess-spatial.sh` ran `--source acag` under ESACCI's job
    name and log directory -- it was preprocessing the wrong source.
  - Several scripts used a `/scratch/.../<wrong_source>_$SLURM_JOB_ID`
    temp-dir inherited from whichever script they were copied from (e.g.
    `berman_mining-preprocess-spatial.sh` used a `glass_...` prefix).
  - A couple of scripts had a memory-limit comment percentage that didn't
    match the actual fraction used in the `bc` expression below it.

Usage:
  python orchestration/slurm/generate_slurm_scripts.py          # write files
  python orchestration/slurm/generate_slurm_scripts.py --check  # drift check, no writes; exit 1 if any file would change

Scripts intentionally NOT covered (left as hand-maintained, standalone
files): assemble_create.sh, assemble_update.sh, demean_modis.sh, analysis.sh,
compress.sh, rechunk-zarr.sh, validate-backbone-subset.sh,
modis-preprocess-spatial.sh -- see jobs.yaml's header comment.
"""

import argparse
import difflib
import sys
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
JOBS_FILE = SCRIPT_DIR / "jobs.yaml"

CONDA_HOOK = "/scicore/home/meiera/schulz0022/miniforge-pypy3/bin/conda"
PYTHON_BIN = "/scicore/home/meiera/schulz0022/miniforge-pypy3/envs/src/bin/python"
PROJECT_ROOT = "/scicore/home/meiera/schulz0022/projects/growth-and-temperature"
DEFAULT_DASHBOARD_PORT = 8787

GENERATED_MARKER = (
    "# Generated by orchestration/slurm/generate_slurm_scripts.py from jobs.yaml.\n"
    "# Do not hand-edit -- edit jobs.yaml and regenerate."
)


def render_job(job: dict) -> str:
    name = job["name"]
    log_key = job["log_key"]
    simple = job.get("simple", False)
    debug = job.get("debug", True)
    dashboard_port = job.get("dashboard_port", DEFAULT_DASHBOARD_PORT)

    lines = [
        "#!/bin/bash",
        f"#SBATCH --job-name={name}",
        f"#SBATCH --output=./log/preprocess/{log_key}/%x-%j.out",
        f"#SBATCH --error=./log/preprocess/{log_key}/%x-%j.err",
    ]
    if job.get("partition"):
        lines.append(f"#SBATCH --partition={job['partition']}")
    lines += [
        f"#SBATCH --time={job['time']}",
        f"#SBATCH --qos={job['qos']}",
        f"#SBATCH --cpus-per-task={job.get('cpus', 8)}",
        f"#SBATCH --mem={job['mem']}",
        "",
        GENERATED_MARKER,
        "",
        f'mkdir -p "./log/preprocess/{log_key}"',
        f"cd {PROJECT_ROOT}",
        "",
        "# Activate conda environment",
        f'eval "$({CONDA_HOOK} shell.bash hook)"',
        "conda activate src",
        "",
    ]

    if not simple:
        mem_fraction = job["mem_fraction"]
        mem_pct = int(round(mem_fraction * 100))
        lines += [
            f"# Calculate memory limit (leave some buffer for system - {mem_pct}% of allocated)",
            f'MEMORY_LIMIT_GB=$(echo "scale=0; $SLURM_MEM_PER_NODE * {mem_fraction} / 1024" | bc)',
            "",
        ]

    cmd_parts = [
        f'{PYTHON_BIN} "{PROJECT_ROOT}/run.py" preprocess run',
        f'--config "{PROJECT_ROOT}/orchestration/configs/data.yaml"',
        f"--source {job['source']}",
    ]
    if job.get("subsource"):
        cmd_parts.append(f"--subsource {job['subsource']}")
    cmd_parts.append(f"--stage {job['stage']}")
    cmd_parts.extend(job.get("extra_args", []))
    if not simple:
        cmd_parts += [
            "--dask-threads $SLURM_CPUS_PER_TASK",
            '--dask-memory-limit "${MEMORY_LIMIT_GB}GiB"',
            f'--temp-dir "/scratch/schulz0022/{job["temp_dir_prefix"]}_${{SLURM_JOB_ID}}"',
            f"--dashboard-port {dashboard_port}",
        ]
    if debug:
        cmd_parts.append("--debug")

    lines.append(" \\\n    ".join(cmd_parts))
    lines.append("")
    return "\n".join(lines)


def load_jobs() -> list:
    with open(JOBS_FILE) as f:
        spec = yaml.safe_load(f)
    return spec["jobs"]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="report drift without writing files")
    args = parser.parse_args()

    jobs = load_jobs()
    names_seen = set()
    drift = False

    for job in jobs:
        name = job["name"]
        if name in names_seen:
            print(f"ERROR: duplicate job name {name!r} in jobs.yaml", file=sys.stderr)
            return 1
        names_seen.add(name)

        rendered = render_job(job)
        target = SCRIPT_DIR / f"{name}.sh"

        if args.check:
            existing = target.read_text() if target.exists() else ""
            if existing != rendered:
                drift = True
                print(f"DRIFT: {target.name}")
                diff = difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    rendered.splitlines(keepends=True),
                    fromfile=f"{target.name} (on disk)",
                    tofile=f"{target.name} (generated)",
                )
                sys.stdout.writelines(diff)
        else:
            target.write_text(rendered)
            target.chmod(0o755)
            print(f"wrote {target}")

    if args.check:
        if drift:
            print(f"\n{sum(1 for _ in names_seen)} job(s) checked -- drift found, run without --check to regenerate.")
            return 1
        print(f"{len(names_seen)} job(s) checked -- no drift.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
