#!/bin/bash
#SBATCH --job-name=ntl_harm-grid
#SBATCH --output=./log/preprocess/ntl_harm/%x-%j.out
#SBATCH --error=./log/preprocess/ntl_harm/%x-%j.err
#SBATCH --time=06:00:00
#SBATCH --qos=6hours
#SBATCH --cpus-per-task=8
#SBATCH --mem=256G

# Generated by orchestration/slurm/generate_slurm_scripts.py from jobs.yaml.
# Do not hand-edit -- edit jobs.yaml and regenerate.

mkdir -p "./log/preprocess/ntl_harm"
cd /scicore/home/meiera/schulz0022/projects/growth-and-temperature

# Activate conda environment
eval "$(/scicore/home/meiera/schulz0022/miniforge-pypy3/bin/conda shell.bash hook)"
conda activate src

# --override toggle -- either of these works:
#   sbatch <this script>.sh --override
#   sbatch --export=ALL,PIPELINE_OVERRIDE=1 <this script>.sh
OVERRIDE_FLAG=""
for _arg in "$@"; do
    if [ "$_arg" = "--override" ]; then
        OVERRIDE_FLAG="--override"
    fi
done
if [ -n "${PIPELINE_OVERRIDE:-}" ]; then
    OVERRIDE_FLAG="--override"
fi

# Calculate memory limit (leave some buffer for system - 60% of allocated)
MEMORY_LIMIT_GB=$(echo "scale=0; $SLURM_MEM_PER_NODE * 0.6 / 1024" | bc)

/scicore/home/meiera/schulz0022/miniforge-pypy3/envs/src/bin/python "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/run.py" pipeline run \
    --config "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/orchestration/configs/data.yaml" \
    --source ntl_harm \
    --step grid \
    $OVERRIDE_FLAG \
    --dask-threads $SLURM_CPUS_PER_TASK \
    --dask-memory-limit "${MEMORY_LIMIT_GB}GiB" \
    --temp-dir "/scratch/schulz0022/ntl_harm_${SLURM_JOB_ID}" \
    --dashboard-port 8787 \
    --debug
