#!/bin/bash
#SBATCH --job-name=plad-preprocess
#SBATCH --output=./log/preprocess/plad/%x-%j.out
#SBATCH --error=./log/preprocess/plad/%x-%j.err
#SBATCH --time=06:00:00
#SBATCH --qos=6hours
#SBATCH --cpus-per-task=8
#SBATCH --mem=128G

# Generated by orchestration/slurm/generate_slurm_scripts.py from jobs.yaml.
# Do not hand-edit -- edit jobs.yaml and regenerate.

mkdir -p "./log/preprocess/plad"
cd /scicore/home/meiera/schulz0022/projects/growth-and-temperature

# Activate conda environment
eval "$(/scicore/home/meiera/schulz0022/miniforge-pypy3/bin/conda shell.bash hook)"
conda activate src

/scicore/home/meiera/schulz0022/miniforge-pypy3/envs/src/bin/python "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/run.py" preprocess run \
    --config "/scicore/home/meiera/schulz0022/projects/growth-and-temperature/orchestration/configs/data.yaml" \
    --source plad \
    --stage spatial \
    --admin-level 2 \
    --debug
