apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CONFIG_MAP_NAME}  # Will be replaced during deployment
data:
  workflow-config.json: |
    {
      "processing_mode": "${PROCESSING_MODE}",
      "dataset": "${DATASET_NAME}",
      "parameters": {
        # Common parameters for both modes
        "gcs_bucket": "growthandheat",
        "project_id": "ee-growthandheat",
        
        # Mode-specific parameters will be merged here from the input JSON
        ${CONFIG_PARAMETERS}
      }
    }