# Unified configuration for GNT data system

# HPC settings
hpc:
  target: "schulz0022@transfer12.scicore.unibas.ch:/scicore/home/meiera/schulz0022/projects/growth-and-temperature/data_nobackup"
  local_index_dir: "C:\\Users\\schulz0022\\hpc_data_index"
  key_file: "Z:\\id_ed25519_scicore"

# Data source configurations
sources:
  # GLASS MODIS LST Daily 1KM
  glass_modis:
    type: "glass_lst"
    base_url: "https://glass.hku.hk/archive/LST/MODIS/Daily/1KM/"
    data_path: "glass/modis/daily"
    
    # Download settings
    download:
      batch_size: 1000
      max_concurrent_downloads: 4
      tar_max_files: 100
      tar_max_size_mb: 500
  
  # EOG DMSP Nightlights
  eog_dmsp:
    type: "eog_dmsp"
    base_url: "https://eogdata.mines.edu/wwwdata/dmsp/v4composites_rearrange/"
    data_path: "eog/dmsp"
    
    # Download settings
    download:
      batch_size: 10
      max_concurrent_downloads: 2
      tar_max_files: 50
      tar_max_size_mb: 300
  
  # EOG VIIRS Annual
  eog_viirs_annual:
    type: "eog_viirs_annual"
    base_url: "https://eogdata.mines.edu/nighttime_light/annual/v21/"
    data_path: "eog/viirs/annual"
    
    # Download settings
    download:
      batch_size: 10
      max_concurrent_downloads: 2
      tar_max_files: 50
      tar_max_size_mb: 300