# Debug configuration for GLASS LST data download with indexing and validation

# Workflow definition
tasks:
  # Second task: Validate index against GCS
  - data_source: "glass"
    mode: "validate"
    bucket_name: "growthandheat"
    
    # Source configuration
    base_url: "https://glass.hku.hk/archive/LST/MODIS/Daily/1KM/"
    file_extensions: [".hdf"]
    
    # Validation options
    force_file_list_update: false        # Force refresh of GCS file list during validation
    
    # Debug settings
    debug: true
    verbose_logging: true

  # Third task: Download files
  - data_source: "glass"
    mode: "download"
    bucket_name: "growthandheat"
    
    # Source configuration
    base_url: "https://glass.hku.hk/archive/LST/MODIS/Daily/1KM/"
    file_extensions: [".hdf"]
    
    # Processing controls
    max_concurrent_downloads: 2
    max_queue_size: 8
    
    # Debug settings
    debug: true
    verbose_logging: true
    
    # Retry settings
    max_retries: 3
    retry_delay: 10
    
    # Download specific options
    skip_existing: true                 # Skip files that already exist in GCS
    batch_size: 5                       # Process files in smaller batches for debugging