# Configuration for EOG data download and indexing

# Workflow definition
tasks:
  # # 1. DMSP nighttime lights data - Index
  # - data_source: "eog"
  #   mode: "index"
  #   bucket_name: "growthandheat"
    
  #   # Source configuration
  #   base_url: "https://eogdata.mines.edu/wwwdata/dmsp/v4composites_rearrange/"
  #   file_extensions: [".global.intercal.stable_lights.avg_vis.tif"]
  #   output_path: "eog/dmsp"
    
  #   # Processing controls
  #   max_concurrent_downloads: 1
  #   max_queue_size: 10
    
  #   # Debug settings
  #   debug: true
  #   verbose_logging: true
    
  #   # Retry settings
  #   max_retries: 3
  #   retry_delay: 10

  # # 2. DMSP nighttime lights data - Download
  # - data_source: "eog"
  #   mode: "download"
  #   bucket_name: "growthandheat"
    
  #   # Source configuration
  #   base_url: "https://eogdata.mines.edu/wwwdata/dmsp/v4composites_rearrange/"
  #   file_extensions: [".global.intercal.stable_lights.avg_vis.tif"]
  #   output_path: "eog/dmsp"
    
  #   # Processing controls
  #   max_concurrent_downloads: 1
  #   max_queue_size: 20
    
  #   # Retry settings
  #   max_retries: 3
  #   retry_delay: 10

  # 3. DMSP nighttime lights data - Validate
  - data_source: "eog"
    mode: "validate"
    bucket_name: "growthandheat"
    force_refresh_gcs: true
    
    # Source configuration
    base_url: "https://eogdata.mines.edu/wwwdata/dmsp/v4composites_rearrange/"
    file_extensions: [".global.intercal.stable_lights.avg_vis.tif"]
    output_path: "eog/dmsp"
    
    # Validation settings
    sample_percentage: 100  # Validate all files (small dataset)
    fix_issues: true        # Attempt to redownload invalid files

  # # 4. VIIRS DVNL data - Index
  # - data_source: "eog"
  #   mode: "index"
  #   bucket_name: "growthandheat"
    
  #   # Source configuration
  #   base_url: "https://eogdata.mines.edu/wwwdata/viirs_products/dvnl/"
  #   file_extensions: [".tif"]
  #   output_path: "eog/dvnl"
    
  #   # Processing controls
  #   max_concurrent_downloads: 1
  #   max_queue_size: 10
    
  #   # Retry settings
  #   max_retries: 3
  #   retry_delay: 10

  # # 5. VIIRS DVNL data - Download
  # - data_source: "eog"
  #   mode: "download"
  #   bucket_name: "growthandheat"
    
  #   # Source configuration
  #   base_url: "https://eogdata.mines.edu/wwwdata/viirs_products/dvnl/"
  #   file_extensions: [".tif"]
  #   output_path: "eog/dvnl"
    
  #   # Processing controls
  #   max_concurrent_downloads: 1
  #   max_queue_size: 20
    
  #   # Retry settings
  #   max_retries: 3
  #   retry_delay: 10

  # # 6. VIIRS DVNL data - Validate
  # - data_source: "eog"
  #   mode: "validate"
  #   bucket_name: "growthandheat"
  #   force_refresh_gcs: true
    
  #   # Source configuration
  #   base_url: "https://eogdata.mines.edu/wwwdata/viirs_products/dvnl/"
  #   file_extensions: [".tif"]
  #   output_path: "eog/dvnl"
    
  #   # Validation settings
  #   sample_percentage: 100  # Validate all files
  #   fix_issues: true        # Attempt to redownload invalid files

  # # 7. VIIRS Annual Stable Lights data - Index
  # - data_source: "eog"
  #   mode: "index"
  #   bucket_name: "growthandheat"
    
  #   # Source configuration
  #   base_url: "https://eogdata.mines.edu/nighttime_light/annual/v21/"
  #   file_extensions: ["median_masked.dat.tif.gz"]
  #   output_path: "eog/viirs"
    
  #   # Processing controls
  #   max_concurrent_downloads: 1
  #   max_queue_size: 10
    
  #   # Retry settings
  #   max_retries: 3
  #   retry_delay: 10

  # # 8. VIIRS Annual Stable Lights data - Download
  # - data_source: "eog"
  #   mode: "download"
  #   force-refresh: true
  #   bucket_name: "growthandheat"
    
  #   # Source configuration
  #   base_url: "https://eogdata.mines.edu/nighttime_light/annual/v21/"
  #   file_extensions: ["median_masked.dat.tif.gz"]
  #   output_path: "eog/viirs"
    
  #   # Processing controls
  #   max_concurrent_downloads: 1
  #   max_queue_size: 20
    
  #   # Retry settings
  #   max_retries: 3
  #   retry_delay: 10

  # # 9. VIIRS Annual Stable Lights data - Validate
  # - data_source: "eog"
  #   mode: "validate"
  #   bucket_name: "growthandheat"
  #   force_refresh_gcs: true
    
  #   # Source configuration
  #   base_url: "https://eogdata.mines.edu/nighttime_light/annual/v21/"
  #   file_extensions: ["median_masked.dat.tif.gz"]
  #   output_path: "eog/viirs"
    
  #   # Validation settings
  #   sample_percentage: 100  # Validate all files
  #   fix_issues: true        # Attempt to redownload invalid files
