tasks:
  - preprocessor: glass
    stage: "stage1"
    data_source: "AVHRR"
    years: [1992, 2013]
    base_url: "https://eogdata.mines.edu/wwwdata/dmsp/v4composites_rearrange/"
    file_extensions: [".hdf"]
    dask_threads: 2
    dask_memory_limit: "4GB"
    chunk_size: 
      time: 1
      x: 500
      y: 500
    override: true