tasks:
  - preprocessor: misc
    # Basic settings
    bucket_name: growthandheat
    data_path: auxiliary/boundaries
    output_path: auxiliary/boundaries
    
    # Processing parameters
    simplify_tolerance: 0.001  # ~100m at equator - simplifies polygons
    rasterize: true
    version: v1
    
    # Dask configuration for parallel processing
    dask_threads: 2  # Use 2 threads for debugging (increase for production)
    dask_memory_limit: 4GB  # Limit memory usage for testing
    
    # For testing specific functionality
    override: true  # Force reprocessing even if files exist